services:
  - type: web
    name: subtool-saas
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
      - fromGroup: subtool-secrets # Reference to your Secret Group

cronJobs:
  - name: nightly-tasks
    schedule: "0 0 * * *" # Runs every day at midnight
    command: "curl '${RENDER_EXTERNAL_URL}/api/internal/cron?secret=${CRON_SECRET}'"
